---
- name: Fetch repository signing key
  ansible.builtin.get_url:
    url: "{{ apt_repository.url }}"
    dest: "{{ apt_repository.save_directory }}/{{ apt_repository.name }}.{{ apt_repository.file_extension }}"
  # with_items: "{{ [ aptSigningKeys ] | community.general.lists_mergeby( hostConfig.aptSigningKeys | default(''), 'name', list_merge = 'replace' ) }}"
  # when:
  #   - ansible_os_family == 'Debian'


- name: Add apt repository
  apt_repository:
    repo: "{{ apt_repository.repo }}"
    state: present
    filename: "{{ apt_repository.name }}"
  register: apt_repository_add
  # with_items: "{{ [ aptRepositories ] | community.general.lists_mergeby(hostConfig.aptRepositories|default(''), 'name', list_merge='replace') }}"
  # when:
  #   - ansible_os_family == 'Debian'


- name: Apt Update
  when: apt_repository_add.changed | default(false) | bool
  block:


    - name: Apt cache update
      ansible.builtin.apt:
        update_cache: true
      register: apt_cache_update


  rescue:


    - name: APT Clean
      ansible.builtin.command:
        cmd: apt-get Clean
      changed_when: false
      failed_when: false
      when: apt_cache_update.rc | int == 100


    - name: APT remove cache
      ansible.builtin.command:
        cmd: rm -rf /var/lib/apt/lists/*
      changed_when: false
      failed_when: false
      when: apt_cache_update.rc | int == 100


    - name: Apt cache update
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: apt_cache_update.rc | int == 100


    - name: Force error on unrecognized
      ansible.builtin.assert:
        that:
          - apt_cache-update.rc | int != 100
        msg: APT Update unknown error
      when: apt_cache-update.rc | int != 100


# - name: Clear task variables
#   ansible.builtin.set_fact:
#     aptRepositories: []
#     aptSigningKeys: []
