---
# As this role is to be included in playbooks with ``, this will gather the facts for the play and only once
- name: Gather facts
  ansible.builtin.gather_facts:
  when: common_gather_facts | bool


- name: Debian Based hosts
  ansible.builtin.include_tasks:
    file: debian.yaml
    apply:
      tags:
        - always
  when: ansible_os_family == 'Debian'
  tags:
    - always

- name: Gather host details for ITSM
  ansible.builtin.include_tasks:
    file: stats_computer.yaml
    apply:
      tags:
        stats_hosts
  tags:
    - never
    - stats_hosts
