---
- name: RebootHost
  ansible.builtin.reboot:
    reboot_timeout: 300
  when: ansible_connection == 'ssh'


- name: Reboot Host network change
  # ansible.builtin.set_fact:
  #   ansible_host: "{{ hostDetails.network.ipaddress }}"
  #   cacheable: yes
  ansible.builtin.reboot:
    reboot_timeout: 300
  listen: reboot_host
  when: ansible_connection == 'ssh'

- name: Rmmodipv6
  ansible.builtin.command: rmmod ipv6
  failed_when: false

- name: Reload resolver config
  ansible.builtin.shell:
    cmd:
      resolvconf --enable-updates;
      resolvconf -u
    executable: /bin/bash
  changed_when: false
  listen: reload_resolver
  when: ansible_os_family == 'Debian'


- name: Restart time sync service
  ansible.builtin.service:
    name: systemd-timesyncd.service
    state: restarted
  listen: restart_timesyncd
