---

- name: Set Hostname
  ansible.builtin.hostname:
    name: |-
      {%- if
        '.' in inventory_hostname
      -%}
        {{ (inventory_hostname | split('.'))[0] }}
      {%- else -%}
        {{ inventory_hostname }}
      {%- endif %}
    use: debian
  notify: RebootHost


- name: Trigger reboot if required
  ansible.builtin.meta: flush_handlers
